version: '3.1'

services:
#  db: // not needed for now
#    image: postgres
#    restart: unless-stopped
#    environment:
#      POSTGRES_DB: tictactoe_db
#      POSTGRES_USER: tictactoe_admin
#      POSTGRES_PASSWORD: tictactoe$1234
#    ports:
#      - "5432:5432"
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
